# fly.toml app configuration file generated for datingapplication on 2023-05-31T14:35:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapplication"
primary_region = "waw"

[build]
  image = "subzero17707/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="div5ttz7g"
  CloudinarySettings__ApiKey="435957832178395"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
